name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger frontend deploy
        run: curl -X POST "$FRONTEND_DEPLOY_HOOK"
        env:
          FRONTEND_DEPLOY_HOOK: ${{ secrets.FRONTEND_DEPLOY_HOOK }}

      - name: Trigger backend deploy
        run: curl -X POST "$BACKEND_DEPLOY_HOOK"
        env:
          BACKEND_DEPLOY_HOOK: ${{ secrets.BACKEND_DEPLOY_HOOK }}
