version: "3.9"

services:
  backend:
    build: ./backend
    container_name: pulsechain-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL_HOST=redis     
    volumes:
      - ./backend:/app        
      - /app/node_modules          
    command: npx nodemon src/server.js
    depends_on:
      - redis

  frontend:
    build: ./frontend
    container_name: pulsechain-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  redis:        
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
